# -*- coding: utf-8 -*-
"""milestone 1 and 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkuQMeY2jYiLIQy1cEipJNhcPsp-9y9R
"""

import pandas as pd

# Load the Excel dataset
df = pd.read_excel('customer_support_tickets.xlsx')

# Check the schema and missing values
df.info()

# Check distribution of Ticket Type
print("--- Ticket Type Distribution ---")
print(df['Ticket Type'].value_counts())

# Check distribution of Ticket Priority
print("\n--- Ticket Priority Distribution ---")
print(df['Ticket Priority'].value_counts())

# Check distribution of Product Purchased (Category)
print("\n--- Product/Category Distribution ---")
print(df['Product Purchased'].value_counts())

# Drop 'Customer Email','Resolution','unamed:9' and customer satisfication rating columns
df.drop(columns=['Customer Email', 'Resolution','Unnamed: 9'], inplace=True, errors='ignore')

# Verify the columns are removed
print(df.columns)

# Check the status of the tickets
print(df['Ticket Status'].value_counts())

# Define the mapping for priority scores
priority_map = {
    'Critical': 4,
    'High': 3,
    'Medium': 2,
    'Low': 1
}

# Create the new Priority_Score column
df['Priority_Score'] = df['Ticket Priority'].map(priority_map)

# View the first few rows to confirm the new column
print(df[['Ticket Priority', 'Priority_Score']].head())

# Check counts for each Priority_Score
print("--- Priority Score Counts ---")
print(df['Priority_Score'].value_counts().sort_index())

# Get the frequency count for every Ticket Subject
subject_counts = df['Ticket Subject'].value_counts()

print("--- Ticket Subject Counts ---")
print(subject_counts)

print(f"\nTotal unique subjects: {df['Ticket Subject'].nunique()}")

#to caluculate resolution duration.
df['Resolution_Duration'] = df['Time to Resolution'] - df['First Response Time']

# Convert the duration to days to float for easier analysis
# Tickets not yet closed will result in NaN
df['Resolution_Duration_Days'] = df['Resolution_Duration'].dt.total_seconds() / (24 * 3600)

# Check the new columns for the first few 'Closed' tickets
print("--- Resolution Duration Samples (Days) ---")
print(df[df['Ticket Status'] == 'Closed'][['First Response Time', 'Time to Resolution', 'Resolution_Duration_Days']].head())
negative_tickets = df[df['Resolution_Duration_Days'] < 0]
print(f"Number of tickets with negative duration: {len(negative_tickets)}")

if len(negative_tickets) > 0:
    print("\n--- Examples of Data Errors (Negative Duration) ---")
    print(negative_tickets[['First Response Time', 'Time to Resolution', 'Resolution_Duration_Days']].head())

df = df[(df['Resolution_Duration_Days'] >= 0) | (df['Resolution_Duration_Days'].isna())]


print("\n--- Cleaned Dataset Info ---")
print(f"Remaining rows: {len(df)}")
print(f"Negative values remaining: {(df['Resolution_Duration_Days'] < 0).sum()}")  # Function to convert the duration into a readable string
def format_duration(td):
    if pd.isna(td):
        return "Pending"
    days = td.days
    hours, remainder = divmod(td.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{days} days {hours:02}h:{minutes:02}m"

# Apply the formatting
df['Resolution_Duration_Readable'] = df['Resolution_Duration'].apply(format_duration)

# Check the results for Closed tickets
print("--- Readable Resolution Time ---")
print(df[df['Ticket Status'] == 'Closed'][['Resolution_Duration_Days', 'Resolution_Duration_Readable']].head())

negative_tickets = df[df['Resolution_Duration_Days'] < 0]
print(f"Number of tickets with negative duration: {len(negative_tickets)}")

if len(negative_tickets) > 0:
    print("\n--- Examples of Data Errors (Negative Duration) ---")
    print(negative_tickets[['First Response Time', 'Time to Resolution', 'Resolution_Duration_Days']].head())

df = df[(df['Resolution_Duration_Days'] >= 0) | (df['Resolution_Duration_Days'].isna())]


print("\n--- Cleaned Dataset Info ---")
print(f"Remaining rows: {len(df)}")
print(f"Negative values remaining: {(df['Resolution_Duration_Days'] < 0).sum()}")

# Function to convert the duration into a readable string
def format_duration(td):
    if pd.isna(td):
        return "Pending"
    days = td.days
    hours, remainder = divmod(td.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{days} days {hours:02}h:{minutes:02}m"

# Apply the formatting
df['Resolution_Duration_Readable'] = df['Resolution_Duration'].apply(format_duration)

# Check the results for Closed tickets
print("--- Readable Resolution Time ---")
print(df[df['Ticket Status'] == 'Closed'][['Resolution_Duration_Days', 'Resolution_Duration_Readable']].head())

display(df)

df.to_excel('itsupport(cleaned data).xlsx', index=False)

from google.colab import files
files.download('itsupport(cleaned data).xlsx')

df_excel = df.copy()

# Ensure 'Resolution_Duration' is present in df_excel.
# This makes the export robust even if previous cells were not run in order.
if 'Resolution_Duration' not in df_excel.columns:
    # Check if the necessary base columns are available to calculate Resolution_Duration.
    if 'Time to Resolution' in df_excel.columns and 'First Response Time' in df_excel.columns:
        df_excel['Resolution_Duration'] = df_excel['Time to Resolution'] - df_excel['First Response Time']
    else:
        print("Warning: Cannot calculate 'Resolution_Duration' as 'Time to Resolution' or 'First Response Time' columns are missing.")
        # If we cannot calculate, we will fill 'Resolution_Duration_Minutes' with NaNs later.
        df_excel['Resolution_Duration'] = pd.NaT # Not a Time for timedelta column

# Now, calculate 'Resolution_Duration_Minutes' if 'Resolution_Duration' is available.
if 'Resolution_Duration' in df_excel.columns:
    # It's possible Resolution_Duration was created but might contain NaT if base columns were missing.
    # .dt.total_seconds() will correctly handle NaT, resulting in NaN.
    df_excel['Resolution_Duration_Minutes'] = df_excel['Resolution_Duration'].dt.total_seconds() / 60
else:
    # This case should ideally not be reached if the above 'if' block works as expected.
    # It serves as a final fallback.
    df_excel['Resolution_Duration_Minutes'] = pd.NA

df_excel.to_excel('cleaned data.xlsx', index=False)
from google.colab import files
files.download('cleaned data.xlsx')

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

# 1.Ticket Type Distribution
plt.figure(figsize=(9, 6))
sns.countplot(
    data=df,
    x='Ticket Type',
    palette='viridis',
    order=df['Ticket Type'].value_counts().index
)

plt.title('Ticket Distribution by Type', fontsize=15)
plt.xlabel('Ticket Type', fontsize=10)
plt.ylabel('Number of Tickets', fontsize=12)

plt.savefig('ticket_type_distribution.png')

plt.show()

# 2.Ticket Priority Distribution
plt.figure(figsize=(10, 6))
sns.countplot(
    data=df,
    x='Ticket Priority',
    palette='magma',
    order=['Critical', 'High', 'Medium', 'Low']
)

plt.title('Ticket Distribution by Priority', fontsize=15)
plt.xlabel('Priority Level', fontsize=12)
plt.ylabel('Number of Tickets', fontsize=12)

plt.show()

# 3.Top 10 Products by Ticket Volume
plt.figure(figsize=(10, 8))

top_10_products = df['Product Purchased'].value_counts().nlargest(10).index

sns.countplot(
    data=df[df['Product Purchased'].isin(top_10_products)],
    y='Product Purchased',
    palette='rocket',
    order=top_10_products
)

plt.title('Top 10 Product Categories by Ticket Volume', fontsize=15)
plt.xlabel('Number of Tickets', fontsize=12)
plt.ylabel('Product Name', fontsize=12)


plt.show()

# 4. Three-way Status Pie Chart
plt.figure(figsize=(9, 9))

status_counts = df['Ticket Status'].value_counts()

colors = ['#ff9999','#66b3ff','#99ff99']

plt.pie(
    status_counts,
    labels=status_counts.index,
    autopct='%1.1f%%',
    startangle=90,
    colors=colors,
    pctdistance=0.85,
    explode=(0.05, 0.05, 0.05)
)


plt.title('Current Workload Composition (Status)', fontsize=15)
plt.show()

# 5. Resolution Time Distribution
plt.figure(figsize=(12, 6))

# Calculate Resolution_Duration_Minutes for the main df
df['Resolution_Duration_Minutes'] = df['Resolution_Duration'].dt.total_seconds() / 60

closed_tickets = df[df['Ticket Status'] == 'Closed']

sns.histplot(closed_tickets['Resolution_Duration_Minutes'], bins=30, kde=True, color='teal')


plt.title('Distribution of Resolution Time (Minutes)', fontsize=15)
plt.xlabel('Minutes to Resolve', fontsize=12)
plt.ylabel('Number of Tickets', fontsize=12)

plt.show()

# frequency count for every Product
product_counts = df['Product Purchased'].value_counts()


print("--- Product Ticket Counts ---")
print(product_counts)

print(f"\nTotal unique products: {df['Product Purchased'].nunique()}")

# 6.Product vs. Priority (grouped bar chart)
plt.figure(figsize=(14, 8))

top_products = df['Product Purchased'].value_counts().nlargest(10).index
df_top_products = df[df['Product Purchased'].isin(top_products)]

sns.countplot(
    data=df_top_products,
    x='Product Purchased',
    hue='Ticket Priority',
    palette='viridis',
    order=top_products
)

plt.title('Ticket Volume by Product and Priority Level', fontsize=15)
plt.xlabel('Product Name', fontsize=12)
plt.ylabel('Number of Tickets', fontsize=12)
plt.legend(title='Priority Level')

plt.xticks(rotation=45)

plt.show()

# a  clustering function
def categorize_issue(subject):
    subject = str(subject).lower()
    if any(word in subject for word in ['bug', 'error', 'crash', 'fail', 'broken']):
        return 'Software Bug'
    if any(word in subject for word in ['security', 'password', 'login', 'access', 'hack', 'auth']):
        return 'Security/Access'
    if any(word in subject for word in ['api', 'connect', 'integration', 'sync', 'bridge']):
        return 'Integration'
    if any(word in subject for word in ['billing', 'refund', 'payment', 'price', 'invoice']):
        return 'Billing/Finance'
    return 'General Inquiry'

df['Issue_Cluster'] = df['Ticket Subject'].apply(categorize_issue)


plt.figure(figsize=(10, 6))
order = df['Issue_Cluster'].value_counts().index
sns.countplot(data=df, y='Issue_Cluster', palette='coolwarm', order=order)

plt.title('Common Issue Categories (Root Cause Clusters)', fontsize=15)
plt.xlabel('Number of Tickets', fontsize=12)
plt.ylabel('Issue Category', fontsize=12)
plt.show()

# Create a Cross-tabulation of Product and Priority
pivot_table = pd.crosstab(df['Product Purchased'], df['Ticket Priority'])

cols = [c for c in ['Critical', 'High', 'Medium', 'Low'] if c in pivot_table.columns]
pivot_table = pivot_table[cols]

# Heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(pivot_table, annot=True, fmt="d", cmap="YlOrRd", cbar_kws={'label': 'Ticket Count'})

plt.title('Product Risk Heatmap: Volume vs. Priority', fontsize=16, fontweight='bold')
plt.xlabel('Priority Level', fontsize=12)
plt.ylabel('Product Name', fontsize=12)

plt.show()

counts = df['Issue_Cluster'].value_counts()
print(counts)

plt.figure(figsize=(8, 5))
counts.plot(kind='barh', color='skyblue')

plt.title('Tickets per Cluster')
plt.xlabel('Count')
plt.show()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Create a list to store our findings
sim_results = []

# We check each cluster one by one
for cluster in df['Issue_Cluster'].unique():
    # Get the subjects for this specific cluster
    subjects = df[df['Issue_Cluster'] == cluster]['Ticket Subject']

    if len(subjects) > 1:
        # Turn text into numbers so the computer can 'read' them
        vectorizer = TfidfVectorizer()
        tfidf_matrix = vectorizer.fit_transform(subjects)

        # Compare every ticket to every other ticket in the group
        matrix = cosine_similarity(tfidf_matrix)

        # Find the average score (ignoring the 1.0s where a ticket matches itself)
        avg = (np.sum(matrix) - len(subjects)) / (len(subjects)**2 - len(subjects))
        sim_results.append({'Cluster': cluster, 'Score': avg})

# Display the results in a simple table
similarity_df = pd.DataFrame(sim_results).sort_values(by='Score', ascending=False)
print(similarity_df)

import seaborn as sns
import matplotlib.pyplot as plt

# Compare Resolution Time across our clusters
plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Resolution_Duration_Minutes', y='Issue_Cluster', palette='Set2')

plt.title('Performance Gap: Time to Resolve by Issue Type')
plt.xlabel('Minutes until Resolved')
plt.ylabel('Issue Category')
plt.show()

# Calculate the average time for each group
pivot_data = df.pivot_table(
    index='Issue_Cluster',
    columns='Ticket Priority',
    values='Resolution_Duration_Minutes',
    aggfunc='mean'
)

# Reorder priorities to go from Low to Critical
cols = [c for c in ['Low', 'Medium', 'High', 'Critical'] if c in pivot_data.columns]
pivot_data = pivot_data[cols]

plt.figure(figsize=(10, 6))
sns.heatmap(pivot_data, annot=True, fmt=".0f", cmap="YlOrRd")

plt.title('Average Resolution Time (Minutes) by Priority')
plt.show()

from collections import Counter
import re
all_text = " ".join(df['Ticket Subject'].dropna().str.lower())

words = re.findall(r'\w+', all_text)

stop_words = {'the', 'to', 'is', 'in', 'it', 'for', 'and', 'my', 'with', 'on', 'of', 'a', 'an'}
filtered_words = [w for w in words if w not in stop_words and len(w) > 3]

top_10 = Counter(filtered_words).most_common(10)
word_df = pd.DataFrame(top_10, columns=['Word', 'Frequency'])

plt.figure(figsize=(10, 6))
sns.barplot(data=word_df, x='Frequency', y='Word', palette='cool')
plt.title('Top 10 Keywords Driving Ticket Volume', fontsize=14)
plt.show()

import pandas as pd

# Read the cleaned data Excel file into a DataFrame
df_cleaned = pd.read_excel('cleaned data.xlsx')

# Display the first 5 rows of the new DataFrame
display(df_cleaned.head())

